stages:
  - build
  - deploy

build backend:
  stage: build
  only:
    refs:
      - main
  tags:
    - main
  script:
    - ./gradlew build
    - docker build -t lyhike-nimi ./
    - echo '$DOCKER_PASS'
    - echo '$DOCKER_USER'
    - echo '$DOCKER_PASS' | docker login -u $DOCKER_USER --password-stdin
    - docker image ls
    - docker tag lyhike-nimi:latest lyhike/lyhike-nimi:latest
    - docker push lyhike/lyhike-nimi:latest
deploy backend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - cd ~/veebiprojekt
    - docker-compose down
    - docker-compose up -d
#    - chmod +x ./mvnw
