stages:
  - build
  - deploy

build test-backend:
  stage: build
  only:
    refs:
      - main
  tags:
    - main
  script:
    - ./gradlew build
    - docker build -t lyhike-nimi ./
    - docker tag lyhike-nimi:latest lyhike/lyhike-nimi:latest
    - docker push lyhike/lyhike-nimi:latest
#deploy test-backend:
#  stage: deploy
#  only:
#    refs:
#      - main
#  tags:
#    - main
#  script:
#    - cd /opt/web-project
#    - docker-compose down
#    - docker-compose up -d
#    - chmod +x ./mvnw
